### ISSUE TITLE
Restoring scroll position on back and forward.

### ISSUE THREAD

**Issue by ptshih** [youtube/spfjs#263]
I noticed that SPF currently doesn't have support for restoring scroll position when clicking the browser's back and forward buttons (popstate).

I noticed in the demo there was a use of `window.scroll(0,0)`, but sometimes scrolling to top is not the right UX.

Here is an example of why I feel this is important to the UX of a site:

If a user is browsing a list of articles snippets (with a read more link) and decides to click read more on one of the articles below the fold, after reading the article, the expected behavior when the back button is clicked should be to return the user back to where they had previously scrolled the screen (with the article snippet in view).

The above behavior is even more important when the content below the fold is very long. In this case, clicking the back button and being scrolled back to the top would be extra frustrating.

This is something that I noticed PJAX as well as `medium.com` supports. Just curious if this is something that was planned on the roadmap.

Thanks!

**Comment by nicksay** [comment]
Thanks for opening this issue; I've been meaning to do it myself.  This is absolutely on the roadmap.  (I actually also rolled this functionality into #111 but decided to keep them separate to avoid the complexity of that change.)

This will be in the next release.
