### ISSUE TITLE
SPF and CSP

### ISSUE THREAD

**Issue by tindli** [youtube/spfjs#316]
When SPF adds inline script tags from a response into a page, CSP (content security policy) settings (if set) would block the script from execution.

If scripts pointing to a trusted resource are added, it is not an issue. But thats not always appropriate...
(think about binding code that need to be run directly after inserting new html). 

Using CSP script nonce or hash is not an option; its not supported in CSP1.0 and would need a new page to update its CSP headers - things that are not possible, when performing an AJAX call... I guess.

Is there / what is the intended use of SPF together with CSP?

**Comment by DavidCPhillips** [comment]
CSP integration is unfortunately a known issue. Both for inlined scripts
and trusted resources which might change from page to page.

We've started a discussion with the standards team about updating the
policy dynamically, but it's still solidly in the brainstorming phase, and
likely won't be a part of the spec for some time. If you're interested, you
can see the start of the thread here:

https://lists.w3.org/Archives/Public/public-webappsec/2015Jan/0212.html

In the meantime, I believe the typical approach is a combination of
allowing 'unsafe-inline' for inlined scripts and specifying the full
breadth of possible trusted resources in the initial policy for various
integrations.

**Comment by tindli** [comment]
Thanks for the answer. The topic is quite challenging and, according to the thread, widespread amongst other (similar) approaches. 

Its a bit sad, that using SPF collides with the ideas behind CSP but that seems to be the price for
the advantages and flexibility this library provides...

Anyway: starting the discussion to get a more flexible CSP approach in the 
future is a good thing - thanks for that... lets hope to find a good solution together.

With this issue, I just wanted to raise awareness for this topic as I was not sure, how SPF handles
CSP restrictions. 

I will close this issue soon, as the further discussion will most likely focus on how to adapt CSP... If there are other suggestions/ideas/thoughts, please bring them up.

**Comment by tindli** [comment]
closing this issue now... lets see how CSP evolves over time.
