### ISSUE TITLE
In the background, cached/prefetched navigation can be slower than standard navigation

### ISSUE THREAD

**Issue by nicksay** [youtube/spfjs#337]
This particularly affects WebKit browsers: in the background, cached/prefetched navigation can be slower than standard navigation.

When  `document.visibilityState == 'hidden'` (e.g. a [background tab or minimized window](https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API)), cached or prefetched navigation can be slower than standard navigation.  For example, if the average `responseStart - navigationStart` time for background standard navigation is 200ms, then the average background cached/prefetched `responseStart - navigationStart` time will be 1000ms.  This 1000ms delay is very consistent because the [`spf.nav.request.handleResponseFromCache_`](https://github.com/youtube/spfjs/blob/v2.2.0/src/client/nav/request.js#L111) function is executed asynchronously and WebKit forces DOM timers to execute on 1s intervals for `hidden` documents (see [`DOMTimer::hiddenPageAlignmentInterval`](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/frame/DOMTimer.cpp&sq=package:chromium&dr=CSs&rcl=1432122167&l=55))

**Comment by TheSisb** [comment]
Sorry to hijack this issue but not sure where else to ask.  Really interesting project, just wanted to mention the docs for caching and prefetching have been lacking for some time.  Any timeline for when they will get filled in?  Really curious to use this in my next project.
Thanks

**Comment by nicksay** [comment]
@TheSisb Thanks for bumping the docs issue.  Follow #208 for the caching docs and #210 for the prefetching docs.  We'll have something up very soon!
