### ISSUE TITLE
build spf package on windows

### ISSUE THREAD

**Issue by dockbiz** [youtube/spfjs#358]
I tried to build spf package but on  'configure.js' file on rules function "jscompile"  ,.I think cat subcommand it disturb closure complier subcommand. How to fix it?

**Comment by dockbiz** [comment]
I found out to fix it

**Comment by rviscomi** [comment]
@dockbiz  in case others have a similar issue, could you comment on the solution?

**Comment by dockbiz** [comment]
I fixed on bin/configure.js by comment on requirements function and set new parameter on  rule function on line -> jscompile :[ 'java -jar $jscompiler_jar $flags $in --js_output_file $out'] .
