### ISSUE TITLE
auto repeat!

### ISSUE THREAD

**Issue by AhmedLuLu** [youtube/spfjs#404]
Why is there no auto repeat button in the video?

I guess it should be!

**Comment by DavidCPhillips** [comment]
Hi Ahmed,

This sounds like feedback for YouTube, not the SPF library. The best place to submit that kind of feedback is on the YouTube home page.

1. Go to www.youtube.com
2. At the bottom of the page click 'Send Feedback'
3. Follow the instructions to report any recommendations.

Thanks
