### ISSUE TITLE
What pages still use SPF?

### ISSUE THREAD

**Issue by aubymori** [youtube/spfjs#464]
In issue #454 someone said YouTube is moving away from SPF. Which pages still use SPF?

**Comment by tech234a** [comment]
It would be useful to see a live example of the library in use if it is still active anywhere on YouTube.

**Comment by drveresh** [comment]
> It would be useful to see a live example of the library in use if it is still active anywhere on YouTube.

I am also looking for it, and hoping to see some enhancement around it.

**Comment by ShalokShalom** [comment]
Since there are no updates anymore, how does it matter?

**Comment by aubymori** [comment]
I've found out something.
SPF was used on YouTube's 2013-2020 "Hitchhiker" layout for smooth navigation and loading some popups.
SPF is still used on the current Polymer/Kevlar for god knows what.
